openapi: 3.0.0
info:
  title: Model Service API
  version: 1.0.0
  description: |
    API для управления и работы с моделями машинного обучения.
paths:
  /model_classes:
    get:
      summary: "Получить список доступных классов моделей"
      description: "Возвращает список классов моделей, которые могут быть использованы для создания и обучения."
      responses:
        '200':
          description: "Список классов моделей успешно получен"
  /model/create:
    post:
      summary: "Создать новую модель"
      description: "Создает новую модель с указанными параметрами и добавляет её в список доступных моделей."
      requestBody:
        description: "Информация о создаваемой модели"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddModelRequest'
      responses:
        '200':
          description: "Модель успешно создана"
  /model/remove:
    post:
      summary: "Удалить модель"
      description: "Удаляет существующую модель на основе указанных класса и имени."
      requestBody:
        description: "Данные модели для удаления"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveModelRequest'
      responses:
        '200':
          description: "Модель успешно удалена"
  /model/train:
    post:
      summary: "Обучить модель"
      description: "Запускает обучение модели с использованием указанных данных."
      requestBody:
        description: "Информация о модели и данных для обучения"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainRequest'
      responses:
        '200':
          description: "Модель успешно обучена"
  /model/predict:
    post:
      summary: "Сделать предсказание"
      description: "Выполняет предсказание на основе обученной модели и входных данных."
      requestBody:
        description: "Информация о модели и данных для предсказания"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictRequest'
      responses:
        '200':
          description: "Успешное предсказание"
components:
  schemas:
    AddModelRequest:
      type: object
      properties:
        model_class:
          type: string
        model_name:
          type: string
        hyperparameters:
          type: object
      required: [model_class, model_name]
    RemoveModelRequest:
      type: object
      properties:
        model_class:
          type: string
        model_name:
          type: string
      required: [model_class, model_name]
    TrainRequest:
      type: object
      properties:
        model_class:
          type: string
        model_name:
          type: string
        data:
          type: object
      required: [model_class, model_name, data]
    PredictRequest:
      type: object
      properties:
        model_class:
          type: string
        model_name:
          type: string
        data:
          type: object
      required: [model_class, model_name, data]